name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # executa todos os dias à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: CleitonQ
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg

      - name: Push the generated files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generated snake animation"
